### ISSUE TITLE
Not working in Windows

### ISSUE THREAD

**Issue by sitiom** [arahatashun/vscode-actionlint#1]
I have [`actionlint`](https://scoop.sh/#/apps?q=actionlint&s=0&d=1&o=true) installed via Scoop on Windows. However, the lint messages do not appear.

See example below. Running `actionlint` from the command line works just fine but they do not appear from the file itself (the other error is from the yaml extension):
![image](https://user-images.githubusercontent.com/56180050/177264234-07649132-fcc2-4682-bafa-818b448485ae.png)

**Comment by arahatashun** [comment]
@sitiom Could you tell me which version of actionlint you are using?

**Comment by sitiom** [comment]
Here is the output from `actionlint --version`

```console
> actionlint --version
1.6.15
installed by downloading from release page
built with go1.18.3 compiler for windows/amd64
```

**Comment by arahatashun** [comment]
This extension requires actionlint >= v1.6.14 and files must be placed under .github/workflows/. It seems your environment satisfiess both requirements 🤔 .  Currently, I have no idea why it is not working, but I have not tested my extension in Windows.

**Comment by arahatashun** [comment]
This software checks the path to determine whether this file is a GitHub Actions Workflow file or not. I suspect this line of code might not work in Windows.
https://github.com/arahatashun/vscode-actionlint/blob/dcc081c6a4e1fb235095b45ea3dbb4c325f0dc8e/src/extension.ts#L13

**Comment by sitiom** [comment]
Even after the regex change in https://github.com/arahatashun/vscode-actionlint/commit/836896552da02fbf8066c3d3281065191f84821f, it still doesn't work.

**Comment by arahatashun** [comment]
Thank you for reporting the problem. Actually,  I do not have access to Windows computers now 😭 .

**Comment by sitiom** [comment]
@arahatashun Can you bring back the `.github/workflows` regex? The [Github docs](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) clearly specify that `.github/workflows` is the default folder for all workflows.

I have encountered a similar error in a Neovim plugin (https://github.com/jose-elias-alvarez/null-ls.nvim/pull/986), which is also about actionlint as well. Turns out backward slashes are required for Windows. Maybe that helps.

**Comment by arahatashun** [comment]
@sitiom 
I know all GitHub actions files are located under `.github/workflows`. However, I am using a multi-root workspace which has ,github/ as a root. Because of this, I change the regex. Do you have any problems caused by this change?


>Can you bring back the .github/workflows regex? The [Github docs](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) clearly specify that .github/workflows is the default folder for all workflows

**Comment by arahatashun** [comment]
@sitiom 
What change of regex are you suggesting here?
> I have encountered a similar error in a Neovim plugin (https://github.com/jose-elias-alvarez/null-ls.nvim/pull/986), which is also about actionlint as well. Turns out backward slashes are required for Windows. Maybe that helps.

**Comment by sitiom** [comment]
> I know all GitHub actions files are located under `.github/workflows`. However, I am using a multi-root workspace which has ,github/ as a root. Because of this, I change the regex.

Oh ok, that makes sense. Keep it as is, then.

> @sitiom What change of regex are you suggesting here?

It looks like the current regex already accounts for backward slashes, so I'm not sure what's the problem.

**Comment by ishowta** [comment]
Maybe this is the cause.
https://github.com/fnando/vscode-linter/issues/17

**Comment by sitiom** [comment]
It seems to be working now that the upstream issue has been fixed.
